### ISSUE TITLE
in some plays the first heli does not get placed

### ISSUE THREAD

**Issue by ugsusu** [gavboi/btd6-farming#12]
It seems that the script is possibly trying to place the heli too quickly after the deflation popup disappears. The cursor moves to the right spot and clicks, however the heli isn't selected or placed. This does not happen always. Could maybe be fixed by increasing the wait between accepting the popup and placing the first monkey.

**Comment by gavboi** [comment]
Away from my computer for a few days, but I will add an option to increase delay when I'm back👍

**Comment by ugsusu** [comment]
This has for some reason stopped happening in the last versions, so I'll close this issue!
