### ISSUE TITLE
Script doesn't advance level ups / monkey knowledge 

### ISSUE THREAD

**Issue by ugsusu** [gavboi/btd6-farming#14]
The script seems to get stuck whenever there's a level up / monkey knowledge point gained.

**Comment by gavboi** [comment]
ah yes- tried to make it more accessible while the game was running and stopped the constant clicking, but forgot that it was used for something 🤦‍♂️I'll revert that change later tonight, and then get a way around it when I have time

**Comment by gavboi** [comment]
should currently be functioning the same as before the resolution fix

**Comment by ugsusu** [comment]
> ah yes- tried to make it more accessible while the game was running and stopped the constant clicking, but forgot that it was used for something 🤦‍♂️I'll revert that change later tonight, and then get a way around it when I have time

Is that maybe something that can be handled with the `PixelGetColor` as well? To be honest I am quite enjoying it the way it is without the constant clicking because it's possible to alt tab between rounds and let it do its magic in the background.

**Comment by gavboi** [comment]
> Is that maybe something that can be handled with the `PixelGetColor` as well? To be honest I am quite enjoying it the way it is without the constant clicking because it's possible to alt tab between rounds and let it do its magic in the background.

I am looking into that at the moment, yes. [Currently what I'm doing](https://github.com/gavboi/btd6-farming/tree/lvl-up-fix) is too sensitive and appears to be triggering randomly so I need to fiddle around with it some more though - technically it works, but I want to use it for tracking level ups too so it needs to be more accurate. I'm running out of chances for testing as well, level ups happen less and less frequently 😅 it may also not like getting tabbed out of, but I'll fix that too before merging to main.

**Comment by gavboi** [comment]
I believe I have a fix merged to main, let me know if it works (it checks for the banner in the "level up" image using `PixelGetColor`). I also added in more protection when tabbing out so hopefully that should still work well.

**Comment by ugsusu** [comment]
> I believe I have a fix merged to main, let me know if it works (it checks for the banner in the "level up" image using `PixelGetColor`). I also added in more protection when tabbing out so hopefully that should still work well.

Absolutely works wonders!! Thank you
