### ISSUE TITLE
Newest updated moved Infernal map to the right

### ISSUE THREAD

**Issue by ugsusu** [gavboi/btd6-farming#15]
Since the newest update there's been two new maps introduced, which caused the Infernal map to move one slot to the right. Because of this, the script tries to select the wrong map.

Also: Just wanted to tell you that this is the best script I've seen so far. Really amazing work!!

**Comment by gavboi** [comment]
LOL unfortunate, I'll fix that now 😂

Thank you!!

**Comment by Darkness7702** [comment]
it wont show up for me
