### ISSUE TITLE
don't restart after update

### ISSUE THREAD

**Issue by szefgg** [gavboi/btd6-farming#16]
after update script play game normally, but when statistic window appear it dont play again

**Comment by gavboi** [comment]
thanks for opening the issue 👍 I'm really busy currently so I can't fix this at the moment, but I have a GUI overhaul planned next for when I have time that hopefully will address this as well

**Comment by szefgg** [comment]
ok, thank you for response.

**Comment by szefgg** [comment]
i tried to  fix it by myself, i made a new png of next button and still dont click next, idk why. Do you have any idea?

**Comment by gavboi** [comment]
Sorry for such a delay, life got busy for a moment, but I'm freshly motivated and back to work on this 😄 

The image search function is very picky, it's possible the buttons were changed and each button appears to be ever so slightly differently shaped anyways so if you still want a quick fix I would recommend trying again but with a smaller image. The idea is to get the smallest image possible that would have the least variance in relation to what you're searching for (e.g. if it changes size, avoid corners) yet also doesn't have the possibility of matching something else by accident. Reading up on GUIs now to work on that overhaul I mentioned a few months back 😅
